name: Continuous Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aiken-lang/setup-aiken@v1
        with:
          version: v1.1.12
      - run: aiken check
        working-directory: contract/onchain
      - run: aiken build
        working-directory: contract/onchain
