name: Run ESLint and Prettier on Pull Request

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "*"

jobs:
  eslint-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18.20.4"

      - name: Install dependencies
        working-directory: src
        run: npm install

      - name: Run ESLint
        working-directory: src
        run: npx eslint .

      - name: Run Prettier
        working-directory: src
        run: npx prettier --check .
